export function bundle(): Record<string, unknown> {
  return {
    contract_version: 1,
    school_profiles: [{
      slug: "example-school",
      institution_slug: "rutgers",
      campus_slug: "new-brunswick",
      name: "Example School",
      short_name: "Example",
      catalog_year: "2026-2027",
      configuration: { default_program_id: "example-major" },
      source_url: "https://example.rutgers.edu/school",
      source_title: "Example school catalog",
      review_status: "reviewed",
      reviewed_at: 1785456000000,
      sort_order: 10,
    }],
    school_curriculum_modules: [{
      school_slug: "example-school",
      module_type: "core_curriculum",
      curriculum_program_id: "example-core-curriculum",
      source_url: "https://example.rutgers.edu/core",
      review_status: "reviewed",
      reviewed_at: 1785456000000,
      sort_order: 10,
    }],
    program_selection_limits: [{
      home_school_slug: "example-school",
      program_type: "major",
      max_selected: 2,
      note: "Two majors are permitted.",
      source_url: "https://example.rutgers.edu/policy",
      verified_at: 1785456000000,
    }],
    program_combination_policies: [{
      policy_key: "example-combination-policy",
      home_school_slug: "example-school",
      program_a_id: "example-major",
      program_a_school_slug: null,
      program_a_type: null,
      program_b_id: null,
      program_b_school_slug: "other-school",
      program_b_type: "minor",
      same_program_family: false,
      decision: "requires_approval",
      note: "Advising approval is required.",
      source_url: "https://example.rutgers.edu/policy",
      verified_at: 1785456000000,
    }],
    double_count_rules: [{
      program_a: "example-major",
      program_b: "other-minor",
      max_shared_credits: 6,
      note: "Six shared credits.",
    }],
    double_count_exceptions: [{
      program_a: "example-major",
      program_b: "other-minor",
      allowed_course_codes: ["01:999:301"],
      note: "Published exception.",
      source_url: "https://example.rutgers.edu/overlap",
      review_status: "reviewed",
      verified_at: 1785456000000,
    }],
    requirement_course_equivalencies: [{
      program_id: "example-major",
      requirement_course_code: "01:999:101",
      equivalent_course_code: "01:999:102",
      note: "Approved substitute.",
      source_label: "Degree Navigator",
      review_status: "reviewed",
    }],
  };
}
