-- Reviewed SAS New Brunswick Philosophy B.A. (program code 730).

INSERT INTO programs (id,name,school_slug,program_slug,type,catalog_year,academic_program_code,degree_type,program_family_id,source_url,review_status,last_scraped_at,requirement_evidence_required)
VALUES ('sasnb-philosophy-major','Philosophy','sasnb','philosophy-major','major','Current official page','730','B.A.','sasnb-philosophy-730','https://philosophy.rutgers.edu/major','reviewed',strftime('%s','now')*1000,1)
ON CONFLICT(id) DO UPDATE SET name=excluded.name,school_slug=excluded.school_slug,program_slug=excluded.program_slug,type=excluded.type,catalog_year=excluded.catalog_year,academic_program_code=excluded.academic_program_code,degree_type=excluded.degree_type,program_family_id=excluded.program_family_id,source_url=excluded.source_url,review_status=excluded.review_status,last_scraped_at=excluded.last_scraped_at,requirement_evidence_required=excluded.requirement_evidence_required;

INSERT INTO program_sources (program_id,source_url,source_title,source_catalog_year,source_scope,accessed_at,note) VALUES
('sasnb-philosophy-major','https://philosophy.rutgers.edu/major','Philosophy Major',NULL,'program_requirements',strftime('%s','now')*1000,'Current department requirements page; no catalog-year boundary stated.'),
('sasnb-philosophy-major','https://sasundergrad.rutgers.edu/majors-and-core-curriculum/major/major-minor-details/philosophy','Philosophy (Major, Minor) | BA',NULL,'program_profile',strftime('%s','now')*1000,'Current SAS profile confirms program code 730 and B.A. path.')
ON CONFLICT(program_id,source_url) DO UPDATE SET source_title=excluded.source_title,source_catalog_year=excluded.source_catalog_year,source_scope=excluded.source_scope,accessed_at=excluded.accessed_at,note=excluded.note;

DELETE FROM program_requirement_evidence WHERE program_id='sasnb-philosophy-major';
DELETE FROM requirement_course_selectors WHERE group_id IN (SELECT id FROM requirement_groups WHERE program_id='sasnb-philosophy-major');
DELETE FROM requirement_courses WHERE group_id IN (SELECT id FROM requirement_groups WHERE program_id='sasnb-philosophy-major');
DELETE FROM requirement_groups WHERE program_id='sasnb-philosophy-major';
DELETE FROM program_eligibility_rules WHERE program_id='sasnb-philosophy-major';

INSERT INTO requirement_groups (id,program_id,parent_group_id,name,rule,count,sort_order,auto_generated) VALUES
('sasnb-philosophy-major-total','sasnb-philosophy-major',NULL,'Eleven Philosophy classroom courses of at least three credits.','min_courses',11,10,0),
('sasnb-philosophy-major-200-level','sasnb-philosophy-major','sasnb-philosophy-major-total','At least one eligible 200-level Philosophy course.','min_courses',1,10,0),
('sasnb-philosophy-major-upper-level','sasnb-philosophy-major','sasnb-philosophy-major-total','At least six eligible 300- or 400-level Philosophy courses.','min_courses',6,20,0),
('sasnb-philosophy-major-logic','sasnb-philosophy-major',NULL,'One Logic course.','min_courses',1,20,0),
('sasnb-philosophy-major-ancient-medieval','sasnb-philosophy-major',NULL,'One Ancient or Medieval Philosophy course.','min_courses',1,30,0),
('sasnb-philosophy-major-modern','sasnb-philosophy-major',NULL,'One Modern Philosophy course.','min_courses',1,40,0),
('sasnb-philosophy-major-ethics-politics','sasnb-philosophy-major',NULL,'One Advanced Ethics or Political Philosophy course.','min_courses',1,50,0),
('sasnb-philosophy-major-theory','sasnb-philosophy-major',NULL,'Two Theory of Knowledge, Metaphysics, Science, Mind/Psychology, or Language courses.','min_courses',2,60,0),
('sasnb-philosophy-major-theory-upper','sasnb-philosophy-major','sasnb-philosophy-major-theory','At least one of those Theory courses at the 400 level.','min_courses',1,10,0);

INSERT INTO requirement_courses (group_id,course_code,note,source_title,source_credits) VALUES
('sasnb-philosophy-major-total','01:190:322','Cross-listed course named by the Philosophy major requirements.',NULL,NULL),('sasnb-philosophy-major-total','01:190:353','Cross-listed course named by the Philosophy major requirements.',NULL,NULL),
('sasnb-philosophy-major-upper-level','01:190:322','Cross-listed 300-level course named by the Philosophy major requirements.',NULL,NULL),('sasnb-philosophy-major-upper-level','01:190:353','Cross-listed 300-level course named by the Philosophy major requirements.',NULL,NULL),
('sasnb-philosophy-major-logic','01:730:109',NULL,NULL,NULL),('sasnb-philosophy-major-logic','01:730:201',NULL,NULL,NULL),('sasnb-philosophy-major-logic','01:730:315',NULL,NULL,NULL),('sasnb-philosophy-major-logic','01:730:407',NULL,NULL,NULL),('sasnb-philosophy-major-logic','01:730:408',NULL,NULL,NULL),
('sasnb-philosophy-major-ancient-medieval','01:730:301',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:302',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:304',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:305',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:306',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:311',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:190:322',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:352',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:190:353',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:401',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:402',NULL,NULL,NULL),('sasnb-philosophy-major-ancient-medieval','01:730:403',NULL,NULL,NULL),
('sasnb-philosophy-major-modern','01:730:307',NULL,NULL,NULL),('sasnb-philosophy-major-modern','01:730:308',NULL,NULL,NULL),('sasnb-philosophy-major-modern','01:730:404',NULL,NULL,NULL),('sasnb-philosophy-major-modern','01:730:405',NULL,NULL,NULL),('sasnb-philosophy-major-modern','01:730:406',NULL,NULL,NULL),('sasnb-philosophy-major-modern','01:730:309',NULL,NULL,NULL),('sasnb-philosophy-major-modern','01:730:416',NULL,NULL,NULL),('sasnb-philosophy-major-modern','01:730:417',NULL,NULL,NULL),
('sasnb-philosophy-major-ethics-politics','01:730:330',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:341',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:342',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:345',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:358',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:441',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:442',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:445',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:450',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:459',NULL,NULL,NULL),('sasnb-philosophy-major-ethics-politics','01:730:470',NULL,NULL,NULL),
('sasnb-philosophy-major-theory','01:730:210',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:215',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:218',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:220',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:225',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:320',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:327',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:328',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:329',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:360',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:370',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:303',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:410',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:412',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:413',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:415',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:418',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:419',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:420',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:421',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:422',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:423',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:424',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:425',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:426',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:427',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:428',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:429',NULL,NULL,NULL),('sasnb-philosophy-major-theory','01:730:435',NULL,NULL,NULL),
('sasnb-philosophy-major-theory-upper','01:730:410',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:412',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:413',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:415',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:418',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:419',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:420',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:421',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:422',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:423',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:424',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:425',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:426',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:427',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:428',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:429',NULL,NULL,NULL),('sasnb-philosophy-major-theory-upper','01:730:435',NULL,NULL,NULL);

-- The published major list identifies each named course as three credits.
UPDATE requirement_courses SET source_credits='3'
WHERE group_id IN (SELECT id FROM requirement_groups WHERE program_id='sasnb-philosophy-major');

INSERT INTO requirement_course_selectors (group_id,selector_key,selector_json,source_url,source_label,review_status,reviewed_at) VALUES
('sasnb-philosophy-major-total','sasnb-philosophy-major-classroom-courses','{"version":1,"kind":"subject_level","school_codes":["01"],"subject_codes":["730"],"course_number_min":100,"course_number_max":499,"minimum_credits":3,"label":"Philosophy classroom courses numbered 100-499 and worth at least three credits"}','https://philosophy.rutgers.edu/major','Philosophy Major','reviewed',strftime('%s','now')*1000),
('sasnb-philosophy-major-200-level','sasnb-philosophy-major-eligible-200-level','{"version":1,"kind":"subject_level","school_codes":["01"],"subject_codes":["730"],"course_number_min":200,"course_number_max":299,"minimum_credits":3,"exclude_course_codes":["01:730:201","01:730:202","01:730:295","01:730:296"],"label":"Eligible 200-level Philosophy courses worth at least three credits"}','https://philosophy.rutgers.edu/major','Philosophy Major','reviewed',strftime('%s','now')*1000),
('sasnb-philosophy-major-upper-level','sasnb-philosophy-major-eligible-upper-level','{"version":1,"kind":"subject_level","school_codes":["01"],"subject_codes":["730"],"course_number_min":300,"course_number_max":499,"minimum_credits":3,"exclude_course_codes":["01:730:495","01:730:496"],"label":"Eligible 300- and 400-level Philosophy courses worth at least three credits"}','https://philosophy.rutgers.edu/major','Philosophy Major','reviewed',strftime('%s','now')*1000)
ON CONFLICT(group_id,selector_key) DO UPDATE SET selector_json=excluded.selector_json,source_url=excluded.source_url,source_label=excluded.source_label,review_status=excluded.review_status,reviewed_at=excluded.reviewed_at;

INSERT INTO program_requirement_evidence (entity_key,program_id,entity_type,group_id,course_code,source_url,source_title,source_catalog_year,accessed_at,reviewer_note,review_status)
SELECT 'group:'||id,'sasnb-philosophy-major','group',id,NULL,'https://philosophy.rutgers.edu/major','Philosophy Major',NULL,strftime('%s','now')*1000,'Current official Philosophy major requirement.','reviewed'
FROM requirement_groups WHERE program_id='sasnb-philosophy-major';
INSERT INTO program_requirement_evidence (entity_key,program_id,entity_type,group_id,course_code,source_url,source_title,source_catalog_year,accessed_at,reviewer_note,review_status)
SELECT 'course:'||group_id||':'||course_code,'sasnb-philosophy-major','course',group_id,course_code,'https://philosophy.rutgers.edu/major','Philosophy Major',NULL,strftime('%s','now')*1000,'Current official Philosophy major requirement.','reviewed'
FROM requirement_courses WHERE group_id IN (SELECT id FROM requirement_groups WHERE program_id='sasnb-philosophy-major');

INSERT INTO program_eligibility_rules (rule_key,program_id,condition_type,condition_value_json,decision,note,source_url,review_status,verified_at) VALUES
('sasnb-philosophy-major-academic-review','sasnb-philosophy-major','advisor_confirmation','{"topics":["no more than three transfer courses toward the major","no more than one D toward the major","department-approved substitutions"]}','requires_approval','Confirm transfer-credit, grade, and substitution decisions with Philosophy advising before relying on this plan.','https://philosophy.rutgers.edu/major','reviewed',strftime('%s','now')*1000)
ON CONFLICT(rule_key) DO UPDATE SET program_id=excluded.program_id,condition_type=excluded.condition_type,condition_value_json=excluded.condition_value_json,decision=excluded.decision,note=excluded.note,source_url=excluded.source_url,review_status=excluded.review_status,verified_at=excluded.verified_at;
